#!/bin/bash

# Color Variables
GREEN='\033[0;32m'
WHITE='\033[1;37m'
NC='\033[0m'

# Remove generated folders
echo -e "${WHITE}Removing unnecessary autogenerated folders and files...${NC}"

# Javascript libraries and frameworks
rm -rf codebase/rdicidr-0.1.0/node_modules codebase/rdicidr-0.1.0/dist codebase/rdicidr-0.1.0/build codebase/rdicidr-0.1.0/out codebase/rdicidr-0.1.0/tmp

echo -e "${GREEN}Unnecessary autogenerated folders and files removed successfully${NC}"

# Get the current directory name
CURRENT_DIR_NAME=$(basename "$PWD")

# Define the name of the zip file with full path
FILE_NAME="$CURRENT_DIR_NAME.zip"
ZIP_FILE_FULL_PATH="$PWD/$FILE_NAME"

echo -e "${WHITE}Compressing challenge into $FILE_NAME...${NC}"

# Compress the remaining files into a zip file using zip
zip -rq "$ZIP_FILE_FULL_PATH" . -x '*.git*' -x '*.DS_Store' -x "$FILE_NAME"

echo -e "${GREEN}Compression complete: $ZIP_FILE_FULL_PATH${NC}"

sleep 2

exit 0
