@echo off
setlocal enabledelayedexpansion

REM Remove generated folders
echo Removing unnecessary autogenerated folders and files

REM Javascript libraries and frameworks
rmdir /s /q codebase\rdicidr-0.1.0\node_modules 2>nul
rmdir /s /q codebase\rdicidr-0.1.0\dist 2>nul
rmdir /s /q codebase\rdicidr-0.1.0\build 2>nul
rmdir /s /q codebase\rdicidr-0.1.0\out 2>nul
rmdir /s /q codebase\rdicidr-0.1.0\tmp 2>nul

echo [32mUnnecessary autogenerated folders and files removed successfully[0m

REM Get the current directory name
for %%i in ("%CD%") do set "CURRENT_DIR_NAME=%%~nxi"

REM Define the name of the zip file with full path
set FILE_NAME=!CURRENT_DIR_NAME!.zip
set ZIP_FILE_FULL_PATH=%CD%\!FILE_NAME!

echo Compressing challenge into !FILE_NAME!

REM Remove .DS_Store files
del /s /q .DS_Store 2>nul

REM Compress the remaining files into a zip file using
REM By default Windows do not include hidden folders like .git
powershell -command "& {Get-ChildItem -Exclude '!FILE_NAME!' | Compress-Archive -DestinationPath '!ZIP_FILE_FULL_PATH!' -Force}"

echo [32mCompression complete: !ZIP_FILE_FULL_PATH![0m

timeout /t 2 /nobreak >nul

exit /b 0
